sudo: required

services:
    - docker

before_install:
    - docker build -t andreib87/docker-react -f Dockerfile.dev .

script:
    - docker run andreib87/docker-react npm run test -- --coverage --watchAll=false